parameters:
    job_name: ''
    image_name: ''
    python_versions: []
    python_architecture: x64
    install_packages: |
        venv/bin/python3 -m pip install --upgrade pip setuptools wheel
        venv/bin/python3 -m pip install tests/licensedcode/data/example_external_licenses/licenses_to_install1


jobs:
    - job: ${{ parameters.job_name }}

      pool:
          vmImage: ${{ parameters.image_name }}

      steps:
          - checkout: self
            fetchDepth: 10

          - ${{ each pyver in parameters.python_versions }}:
              - task: UsePythonVersion@0
                inputs:
                    versionSpec: '${{ pyver }}'
                    architecture: '${{ parameters.python_architecture }}'
                displayName: '${{ pyver }} - Install Python'

              - script: |
                    python${{ pyver }} --version
                    echo "python${{ pyver }}" > PYTHON_EXECUTABLE
                    ./configure --clean && ./configure --dev
                displayName: '${{ pyver }} - Configure'

              - script: ${{ parameters.install_packages }}
                displayName: '${{ pyver }} - Install license'

              - script: venv/bin/pytest -vvs --test-suite=all tests/licensedcode/test_installed_license_detection.py
                displayName: '${{ pyver }} - Run tests'